version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    env_file:
      .env.docker
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    env_file:
      .env.docker
    volumes:
      - ./backend/database/db_init.sql:/docker-entrypoint-initdb.d/db_init.sql:ro
    ports:
      - "5432:5432"
      
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    restart: always
    env_file:
      .env.docker
    ports:
      - "5050:80"  # pgAdmin is accessible at localhost:5050
    depends_on:
      - db

volumes:
  db_data: