version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    env_file:
      .env.docker
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    env_file:
      .env.docker
    volumes: #for persistent data
      - db_data:/var/lib/postgresql/data 
    ports:
      - "5432:5432"

volumes:
  db_data: